// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * ElasticMapsServer represents an Elastic Map Server resource in a Kubernetes cluster.
 */
export class ElasticMapsServer extends pulumi.CustomResource {
    /**
     * Get an existing ElasticMapsServer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ElasticMapsServer {
        return new ElasticMapsServer(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:maps.k8s.elastic.co/v1alpha1:ElasticMapsServer';

    /**
     * Returns true if the given object is an instance of ElasticMapsServer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ElasticMapsServer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ElasticMapsServer.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"maps.k8s.elastic.co/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"ElasticMapsServer" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * MapsSpec holds the specification of an Elastic Maps Server instance.
     */
    public readonly spec!: pulumi.Output<outputs.maps.v1alpha1.ElasticMapsServerSpec | undefined>;
    /**
     * MapsStatus defines the observed state of Elastic Maps Server
     */
    public readonly status!: pulumi.Output<outputs.maps.v1alpha1.ElasticMapsServerStatus | undefined>;

    /**
     * Create a ElasticMapsServer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ElasticMapsServerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "maps.k8s.elastic.co/v1alpha1";
            resourceInputs["kind"] = "ElasticMapsServer";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ElasticMapsServer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ElasticMapsServer resource.
 */
export interface ElasticMapsServerArgs {
    apiVersion?: pulumi.Input<"maps.k8s.elastic.co/v1alpha1">;
    kind?: pulumi.Input<"ElasticMapsServer">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * MapsSpec holds the specification of an Elastic Maps Server instance.
     */
    spec?: pulumi.Input<inputs.maps.v1alpha1.ElasticMapsServerSpecArgs>;
    /**
     * MapsStatus defines the observed state of Elastic Maps Server
     */
    status?: pulumi.Input<inputs.maps.v1alpha1.ElasticMapsServerStatusArgs>;
}
