// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./enterpriseSearch";

// Import resources to register:
import { EnterpriseSearch } from "./enterpriseSearch";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:enterprisesearch.k8s.elastic.co/v1:EnterpriseSearch":
                return new EnterpriseSearch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "enterprisesearch.k8s.elastic.co/v1", _module)
