/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Gateway {
  /**
   * Configuration affecting edge load balancer. See more details at: https://istio.io/docs/reference/config/networking/gateway.html
   */
  spec: {
    selector?: {};
    /**
     * A list of server specifications.
     */
    servers?: {
      bind?: string;
      defaultEndpoint?: string;
      /**
       * One or more hosts exposed by this gateway.
       */
      hosts?: string[];
      /**
       * An optional name of the server, when set must be unique across all servers.
       */
      name?: string;
      port?: {
        /**
         * Label assigned to the port.
         */
        name?: string;
        /**
         * A valid non-negative integer port number.
         */
        number?: number;
        /**
         * The protocol exposed on the port.
         */
        protocol?: string;
        targetPort?: number;
      };
      /**
       * Set of TLS related options that govern the server's behavior.
       */
      tls?: {
        /**
         * REQUIRED if mode is `MUTUAL`.
         */
        caCertificates?: string;
        /**
         * Optional: If specified, only support the specified cipher list.
         */
        cipherSuites?: string[];
        credentialName?: string;
        httpsRedirect?: boolean;
        /**
         * Optional: Maximum TLS protocol version.
         */
        maxProtocolVersion?: "TLS_AUTO" | "TLSV1_0" | "TLSV1_1" | "TLSV1_2" | "TLSV1_3";
        /**
         * Optional: Minimum TLS protocol version.
         */
        minProtocolVersion?: "TLS_AUTO" | "TLSV1_0" | "TLSV1_1" | "TLSV1_2" | "TLSV1_3";
        mode?: "PASSTHROUGH" | "SIMPLE" | "MUTUAL" | "AUTO_PASSTHROUGH" | "ISTIO_MUTUAL";
        /**
         * REQUIRED if mode is `SIMPLE` or `MUTUAL`.
         */
        privateKey?: string;
        /**
         * REQUIRED if mode is `SIMPLE` or `MUTUAL`.
         */
        serverCertificate?: string;
        subjectAltNames?: string[];
        verifyCertificateHash?: string[];
        verifyCertificateSpki?: string[];
      };
    }[];
  };
  status?: {};
  apiVersion: "networking.istio.io/v1beta1";
  kind: "Gateway";
}
