# sudo -E nvim /var/snap/microk8s/current/args/containerd-template.toml
# microk8s stop && microk8s start

  # 'plugins."io.containerd.grpc.v1.cri".registry' contains config related to the registry
  [plugins."io.containerd.grpc.v1.cri".registry]

  # 'plugins."io.containerd.grpc.v1.cri".registry.mirrors' are namespace to mirror mapping for all namespaces.
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:31500"]
      endpoint = ["http://localhost:31500"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.0.1.1:31500"]
       endpoint = ["http://localhost:31500"]
