// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * PostgresCluster is the Schema for the postgresclusters API
 */
export class PostgresCluster extends pulumi.CustomResource {
    /**
     * Get an existing PostgresCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PostgresCluster {
        return new PostgresCluster(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:postgres-operator.crunchydata.com/v1beta1:PostgresCluster';

    /**
     * Returns true if the given object is an instance of PostgresCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PostgresCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PostgresCluster.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"postgres-operator.crunchydata.com/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"PostgresCluster" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * PostgresClusterSpec defines the desired state of PostgresCluster
     */
    public readonly spec!: pulumi.Output<outputs.postgresoperator.v1beta1.PostgresClusterSpec | undefined>;
    /**
     * PostgresClusterStatus defines the observed state of PostgresCluster
     */
    public readonly status!: pulumi.Output<outputs.postgresoperator.v1beta1.PostgresClusterStatus | undefined>;

    /**
     * Create a PostgresCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PostgresClusterArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "postgres-operator.crunchydata.com/v1beta1";
            resourceInputs["kind"] = "PostgresCluster";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.postgresoperator.v1beta1.postgresClusterSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PostgresCluster.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PostgresCluster resource.
 */
export interface PostgresClusterArgs {
    apiVersion?: pulumi.Input<"postgres-operator.crunchydata.com/v1beta1">;
    kind?: pulumi.Input<"PostgresCluster">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * PostgresClusterSpec defines the desired state of PostgresCluster
     */
    spec?: pulumi.Input<inputs.postgresoperator.v1beta1.PostgresClusterSpecArgs>;
    /**
     * PostgresClusterStatus defines the observed state of PostgresCluster
     */
    status?: pulumi.Input<inputs.postgresoperator.v1beta1.PostgresClusterStatusArgs>;
}
