// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./provider";

// Export sub-modules:
import * as agent from "./agent";
import * as apm from "./apm";
import * as beat from "./beat";
import * as elasticsearch from "./elasticsearch";
import * as enterprisesearch from "./enterprisesearch";
import * as kibana from "./kibana";
import * as maps from "./maps";
import * as postgresoperator from "./postgresoperator";
import * as types from "./types";

export {
    agent,
    apm,
    beat,
    elasticsearch,
    enterprisesearch,
    kibana,
    maps,
    postgresoperator,
    types,
};

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("crds", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:crds") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
