// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Agent is the Schema for the Agents API.
 */
export class Agent extends pulumi.CustomResource {
    /**
     * Get an existing Agent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Agent {
        return new Agent(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:agent.k8s.elastic.co/v1alpha1:Agent';

    /**
     * Returns true if the given object is an instance of Agent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Agent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Agent.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"agent.k8s.elastic.co/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"Agent" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * AgentSpec defines the desired state of the Agent
     */
    public readonly spec!: pulumi.Output<outputs.agent.v1alpha1.AgentSpec | undefined>;
    /**
     * AgentStatus defines the observed state of the Agent
     */
    public readonly status!: pulumi.Output<outputs.agent.v1alpha1.AgentStatus | undefined>;

    /**
     * Create a Agent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AgentArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "agent.k8s.elastic.co/v1alpha1";
            resourceInputs["kind"] = "Agent";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Agent.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Agent resource.
 */
export interface AgentArgs {
    apiVersion?: pulumi.Input<"agent.k8s.elastic.co/v1alpha1">;
    kind?: pulumi.Input<"Agent">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * AgentSpec defines the desired state of the Agent
     */
    spec?: pulumi.Input<inputs.agent.v1alpha1.AgentSpecArgs>;
    /**
     * AgentStatus defines the observed state of the Agent
     */
    status?: pulumi.Input<inputs.agent.v1alpha1.AgentStatusArgs>;
}
